esxi_hostname="<hostname>"
esxi_username="root"
esxi_password="<password>"
esxi_datastore="datastore2"
loadcore_agent_image_path="C:\\Users\\Downloads\\LoadCore-Agent-3.4.0.9.ova"
management_network="VM Network"
test_network="Port2"
loadcore_mdw_ip="1.1.1.1"
loadcore_agent_management_interface_name="ens32"
vm_prefix="TF_LoadCore_Agent"
ram=4096
vcpus=4
