esxi_hostname="<hostname>"
esxi_username="root"
esxi_password="<password>"
esxi_datastore="datastore2"
loadcore_mdw_image_path="C:\\Users\\Downloads\\LoadCore-MDW-3.0.0-3304-184.ova"
management_network="VM Network"
vm_prefix="TF_LoadCore"